spring.application.name= higher-secondary-certificate
spring.datasource.url= jdbc:mysql://localhost:3306/student_db
spring.datasource.username= root
spring.datasource.password=
spring.sql.init.mode=always



